# Generated by Django 4.1.7 on 2023-07-22 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_alter_variety_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variety',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
