# Generated by Django 4.1.7 on 2023-07-22 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_alter_variety_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='price',
        ),
    ]
