# Generated by Django 4.1.7 on 2023-07-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_remove_variety_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='variety',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=50),
            preserve_default=False,
        ),
    ]
