# Generated by Django 4.1.7 on 2023-07-22 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_variety_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variety',
            name='price',
        ),
        migrations.AlterField(
            model_name='variety',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
